/* LHS Killough — Faculty Hub site content. Generated by builder.html. */
window.SITE_CONFIG = {
  "site": {
    "campus": "Killough Campus",
    "formsEmbed": "",
    "data": {
      "teacher": {
        "title": "Teacher Reports",
        "embed": "",
        "desc": "Class rosters & grade summaries"
      },
      "admin": {
        "title": "Admin Reports",
        "embed": "",
        "desc": "Campus-wide reports",
        "locked": true
      }
    },
    "nav": {
      "resources": {},
      "forms": {},
      "data": {}
    }
  },
  "groupOrder": [
    "Teaching & Learning",
    "Daily Operations",
    "Staff & Directory",
    "Student Support",
    "Community"
  ],
  "items": [
    {
      "id": "gradebook",
      "label": "Gradebook",
      "group": "Teaching & Learning",
      "icon": "book",
      "daily": true,
      "kind": "link",
      "url": "",
      "desc": "Enter grades & attendance"
    },
    {
      "id": "canvas",
      "label": "Canvas",
      "group": "Teaching & Learning",
      "icon": "monitor",
      "daily": true,
      "kind": "link",
      "url": "https://lisd.instructure.com",
      "desc": "LISD learning management system"
    },
    {
      "id": "eduphoria",
      "label": "Eduphoria / Strive",
      "group": "Teaching & Learning",
      "icon": "clipboard",
      "daily": false,
      "kind": "link",
      "url": "",
      "desc": "PD, LEAD & Assessment"
    },
    {
      "id": "field-trips",
      "label": "Field Trips",
      "group": "Teaching & Learning",
      "icon": "map",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Request & approval forms"
    },
    {
      "id": "bell",
      "label": "Bell Schedule & Lunches",
      "group": "Daily Operations",
      "icon": "bell",
      "daily": true,
      "kind": "embed",
      "embed": "",
      "desc": "Daily schedules & lunch periods"
    },
    {
      "id": "calendar",
      "label": "School Calendar",
      "group": "Daily Operations",
      "icon": "calendar",
      "daily": true,
      "kind": "embed",
      "embed": "",
      "desc": "Campus & district dates"
    },
    {
      "id": "announce",
      "label": "Announcements",
      "group": "Daily Operations",
      "icon": "megaphone",
      "daily": true,
      "kind": "embed",
      "embed": "",
      "desc": "View & submit announcements"
    },
    {
      "id": "smore",
      "label": "Weekly Smore",
      "group": "Daily Operations",
      "icon": "news",
      "daily": true,
      "kind": "embed",
      "embed": "",
      "desc": "This week's campus newsletter"
    },
    {
      "id": "frontline",
      "label": "Absences / Sub",
      "group": "Daily Operations",
      "icon": "clock",
      "daily": true,
      "kind": "link",
      "url": "https://app.frontlineeducation.com",
      "desc": "Report absences & request a sub"
    },
    {
      "id": "student-links",
      "label": "Student Links",
      "group": "Daily Operations",
      "icon": "navigate",
      "daily": true,
      "kind": "embed",
      "embed": "",
      "desc": "Frequently used student sites"
    },
    {
      "id": "drive",
      "label": "Google Drive",
      "group": "Daily Operations",
      "icon": "folder",
      "daily": true,
      "kind": "link",
      "url": "https://drive.google.com",
      "desc": "Shared campus files"
    },
    {
      "id": "outlook",
      "label": "Outlook",
      "group": "Daily Operations",
      "icon": "mail",
      "daily": true,
      "kind": "link",
      "url": "https://outlook.office.com/mail/",
      "desc": "District email"
    },
    {
      "id": "copiers",
      "label": "Copiers",
      "group": "Daily Operations",
      "icon": "printer",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Codes & support"
    },
    {
      "id": "tech",
      "label": "Technology Support",
      "group": "Daily Operations",
      "icon": "support",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Help desk, password resets & guides"
    },
    {
      "id": "handbook",
      "label": "Faculty Handbook",
      "group": "Staff & Directory",
      "icon": "book",
      "daily": true,
      "kind": "reader",
      "src": "handbook.json",
      "url": "https://docs.google.com/document/d/17GXxVF1uWDWxZH5hjcN8eBGDcNodXC0OzqHR0dr9G5U/edit?usp=sharing",
      "desc": "Campus policies & procedures"
    },
    {
      "id": "duty-sched",
      "label": "Duty Schedule",
      "group": "Staff & Directory",
      "icon": "clipboard",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Staff & admin duty assignments"
    },
    {
      "id": "directory",
      "label": "Staff Directory / Phone List",
      "group": "Staff & Directory",
      "icon": "users",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Find a colleague & extensions"
    },
    {
      "id": "admin-info",
      "label": "Admin Contact Info",
      "group": "Staff & Directory",
      "icon": "users",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Who to contact for what"
    },
    {
      "id": "committees",
      "label": "Campus Committees",
      "group": "Staff & Directory",
      "icon": "users",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Committee rosters & sign-ups"
    },
    {
      "id": "mtss",
      "label": "MTSS",
      "group": "Student Support",
      "icon": "layers",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Multi-tiered support process"
    },
    {
      "id": "cis",
      "label": "CIS",
      "group": "Student Support",
      "icon": "compass",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Communities In Schools"
    },
    {
      "id": "nurse",
      "label": "Health Clinic",
      "group": "Student Support",
      "icon": "heart",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Clinic appointments & forms"
    },
    {
      "id": "lunch-app",
      "label": "Free & Reduced Lunch",
      "group": "Student Support",
      "icon": "utensils",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Meal application form"
    },
    {
      "id": "ptsa",
      "label": "PTSA",
      "group": "Community",
      "icon": "heart",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Parent-Teacher-Student Assoc."
    },
    {
      "id": "booster",
      "label": "Booster Club",
      "group": "Community",
      "icon": "star",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Athletic & activity boosters"
    },
    {
      "id": "favorites",
      "label": "Farmer Favorites",
      "group": "Community",
      "icon": "star",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Staff Favorites"
    },
    {
      "id": "history",
      "label": "LHS History & More",
      "group": "Community",
      "icon": "book",
      "daily": false,
      "kind": "embed",
      "embed": "",
      "desc": "Our story since 1897"
    }
  ]
};
